# Generated by Django 3.1 on 2020-08-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnamirocagerencia', '0002_fornecedor_materialfornecedor_materiaprima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='materialfornecedor',
            options={'verbose_name_plural': 'MateriaisFornecedores'},
        ),
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'verbose_name_plural': 'MateriasPrimas'},
        ),
        migrations.AlterModelOptions(
            name='unidademedida',
            options={'verbose_name_plural': 'UnidadesMedidas'},
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='quantidade',
            field=models.FloatField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
